name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ascend/package-lock.json

      - name: Install dependencies
        working-directory: ascend
        run: npm ci

      - name: Lint
        working-directory: ascend
        run: npm run lint

      - name: Typecheck
        working-directory: ascend
        run: npm run typecheck

      - name: Test
        working-directory: ascend
        run: npm test -- --ci --runInBand
